# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-29 07:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('createddate', models.DateTimeField(default=datetime.datetime(2018, 9, 29, 7, 26, 13, 85739))),
            ],
        ),
    ]
